### ISSUE TITLE
I think that the new asc version broke it

### ISSUE THREAD

**Issue by rts7** [Rudokhvist/BoosterCreator#21]
You are probably aware of this, but just in case, the plugin loads normally with the new version but when the 5 minutes pass and it attempts to create boosters, it shuts asc down. This is my log:

2023-12-15 19:33:53|dotnet-12020|FATAL|ASF|OnUnhandledException() System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<ArchiSteamFarm.Web.Responses.HtmlDocumentResponse> ArchiSteamFarm.Steam.Integration.ArchiWebHandler.UrlGetToHtmlDocumentWithSession(System.Uri, System.Collections.Generic.IReadOnlyCollection`1<System.Collections.Generic.KeyValuePair`2<System.String,System.String>>, System.Uri, ERequestOptions, Boolean, Byte, Int32, Boolean)'.
   at BoosterCreator.WebRequest.GetBoosterPage(Bot bot)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at BoosterCreator.WebRequest.GetBoosterPage(Bot bot)
   at BoosterCreator.BoosterHandler.CreateBooster(Bot bot, ConcurrentDictionary`2 gameIDs)
   at BoosterCreator.BoosterHandler.AutoBooster()
   at BoosterCreator.BoosterHandler.<.ctor>b__6_0(Object e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
2023-12-15 19:33:53|dotnet-12020|ERROR|ASF|Exit() Exiting with nonzero error code!
2023-12-15 19:33:53|dotnet-12020|INFO|Microsoft.Hosting.Lifetime|Application is shutting down...

**Comment by Rudokhvist** [comment]
Thank you for the reminder, please check if version 1.3.0.0 works for you.

**Comment by rts7** [comment]
It works, thanks.
