### ISSUE TITLE
ASF v6 upgrade breaks plugin

### ISSUE THREAD

**Issue by dlewis3852** [Rudokhvist/BoosterCreator#23]
Throws the following error at initialization:

2024-03-10 15:14:19|dotnet-7873|ERROR|ASF|InitPlugins() Failed due to error: BoosterCreator, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null
2024-03-10 15:14:19|dotnet-7873|ERROR|ASF|InitPlugins() System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Method 'OnBotInitModules' in type 'BoosterCreator.BoosterCreator' from assembly 'BoosterCreator, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at ArchiSteamFarm.Plugins.PluginsCore.InitPlugins()
System.TypeLoadException: Method 'OnBotInitModules' in type 'BoosterCreator.BoosterCreator' from assembly 'BoosterCreator, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
2024-03-10 15:14:29|dotnet-7873|ERROR|ASF|Exit() Exiting with 1 error code!

**Comment by Rudokhvist** [comment]
Thank you for the report, new release is incoming.

**Comment by Rudokhvist** [comment]
Please check that v.2.0.0.0 works correctly for you with ASF v.6
